### ISSUE TITLE
does ecco s3 access work for arbitrary podaac shortnames

### ISSUE THREAD

**Issue by ifenty** [ECCO-Hackweek/ecco-2024#104]
example TELLUS_GRAC-GRFO_MASCON_CRI_GRID_RL06.1_V3

https://podaac.jpl.nasa.gov/dataset/TELLUS_GRAC-GRFO_MASCON_CRI_GRID_RL06.1_V3

**Comment by andrewdelman** [comment]
Yes it should now, as of #147
