### ISSUE TITLE
add checklist to pcluster getting started page

### ISSUE THREAD

**Issue by ifenty** [ECCO-Hackweek/ecco-2024#47]
@owang01

**Comment by owang01** [comment]
@ifenty I have added two items related to P-Cluster to the [main check list](https://ecco-hackweek.github.io/ecco-2024/preliminary/checklist.html). I also create one local checklist in the [introductory P-Cluster tutorial](https://ecco-hackweek.github.io/ecco-2024/tutorials/pcluster/pcluster-login.html).
